---
driver:
  name: docker

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver_config:
      run_command: /sbin/init

suites:
  - name: default
    run_list:
      - recipe[{{ cookiecutter.cookbook_name }}::default]
