---
driver:
  name: docker

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7
  - name: debian-8

suites:
  - name: default
    run_list:
      - recipe[{{ cookiecutter.project_name }}::default]
    attributes:
