---
driver:
  name: docker
  use_sudo: false
  socket: <%= ENV['DOCKER_HOST'] %>
  privileged: true
  run_command: /sbin/init

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6
    driver_config:
      image: centos:centos6
  - name: centos-7
    driver_config:
      image: centos:centos7
      run_command: /usr/sbin/init

suites:
  - name: default
    run_list:
      - recipe[{{ cookiecutter.cookbook_name }}::default]
